version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 904233128713.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t daggula-api .
      - docker tag daggula-api:latest 904233128713.dkr.ecr.us-east-1.amazonaws.com/daggula-api:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push 904233128713.dkr.ecr.us-east-1.amazonaws.com/daggula-api:latest

artifacts:
  files:
    - '**/*'
