name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: docker build -t daggula-api .

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 904233128713.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Docker Image
        run: |
          docker tag daggula-api:latest 904233128713.dkr.ecr.us-east-1.amazonaws.com/daggula-api:latest
          docker push 904233128713.dkr.ecr.us-east-1.amazonaws.com/daggula-api:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster daggula-cluster --service daggula-service --force-new-deployment

